typography_spectrum: 0.39032084960490465
color:
  brandColors:
    - '#00261C'
    - '#044D29'
    - '#168039'
    - '#45BF55'
    - '#96ED89'
  brandStrength: 0.07520678360015154
  lightness: 0.8726151811424643
  saturation: 0.077474674442783
  rhythmicContrast: 0.003835905808955431
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.39904278749600053
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Phillip Johnson
  email: philjo1005@gmail.com
  url: www.phillipjohnson.org.uk
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/ef4e81fe-8114-4515-80f8-3f9df279e1bd.jpg
name: philjo
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: 23rd Century Poems
    id: c237d359-b7d0-4eb9-a7ab-0b3964df6611
    type: content
  - name: 23rd Century Poems Track Preview
    id: b928ae4d-41bb-4922-b98e-c5b83e1faf95
    type: content
  - name: philjo is back
    id: 95cdcd19-2610-4472-ab4c-8c6774cf3676
    type: content
  - name: Artist of the Month - Ned Rush
    id: e98240ce-ddf5-42c7-a215-3967b15874fb
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/3125412b-02d0-4aaa-8c41-7af60bdb3b58.ico
title: The official website for philjo
description: Electronic music for the future
purpose: []
