name: philjo
favicon: null
layout_spectrum: 0.7413304620422423
typography_spectrum: 0.21219418686814606
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.531202647369355
  lightness: 0.47511643008328974
  saturation: 0.8864098561462015
  rhythmicContrast: 0.2888943839352578
purpose: []
