typography_spectrum: 0.36756784887984395
color:
  brandColors:
    - '#00261C'
    - '#044D29'
    - '#168039'
    - '#45BF55'
    - '#96ED89'
  brandStrength: 0.07520678360015154
  lightness: 0.8726151811424643
  saturation: 0.077474674442783
  rhythmicContrast: 0.003835905808955431
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.39904278749600053
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Phillip Johnson
  email: philjo1005@gmail.com
  url: www.phillipjohnson.org.uk
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/ef4e81fe-8114-4515-80f8-3f9df279e1bd.jpg
name: philjo
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: 23rd Century Poems
    id: c237d359-b7d0-4eb9-a7ab-0b3964df6611
    type: content
favicon: null
title: The official website for philjo
purpose: []
