typography_spectrum: 0.1279
color:
  brandColors:
    - '#000000'
    - '#7e7e7e'
    - '#595959'
    - '#9f9f9f'
    - '#c2c2c2'
  brandStrength: 0
  lightness: 0.5625
  saturation: 0
  rhythmicContrast: 1
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Phillip Johnson
  email: philjo1005@gmail.com
  url: www.phillipjohnson.org.uk
name: philjo
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: The official website for philjo
purpose: []
