name: philjo
favicon: null
layout_spectrum: 0.72486
typography_spectrum: 0.1279
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#7e7e7e'
    - '#595959'
    - '#9f9f9f'
    - '#c2c2c2'
  brandStrength: 0
  lightness: 0.4375
  saturation: 0.5625
  rhythmicContrast: 0.5
purpose: []
